---
title: "JStanfield-Assignment-5"
author: "James Stanfield"
date: "2/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

c("tidyverse",
  "plotly",
  "data.table",
  "ggthemes",
  "data.table"
  
  ) -> package_names  
for(package_name in package_names) {
  if(!is.element(package_name, installed.packages()[,1])) {
     install.packages(package_name,
                      repos = "http://cran.mtu.edu/")
  }
  library(package_name, character.only=TRUE,
          quietly=TRUE,verbose=FALSE)
}

rm(list=c("package_name", "package_names")) # clean up the environment
```

#Question:

How have Disney's mergers and acquisitions of major properties affected or not affected the stock price?

#Data

Data from:
https://finance.yahoo.com/quote/DIS/history?period1=946684800&period2=1580083200&interval=1wk&filter=history&frequency=1wk

Great site for easy stock data.

#Load Data

```{r load disney stock data}
fread(file = "C:/Users/Richard/Documents/Data Science/GDAT515/Jstanfield-Assignment2/DIS.csv") -> dis

str(dis)
```

```{r time series of Disney open}
dis %>%
  select(Date, Open) -> dis.data

as.Date(dis.data$Date, "%m/%d/%Y") -> dis.data$Date

str(dis.data)
```

#Plotly

```{r}

plot_ly(data = dis.data, x = ~Date, y = ~Open, type = "scatter")

```

```{r}

plot_ly(data = dis.data, x = ~Date, y = ~Open, mode = "lines+markers") %>% 
  add_trace(p = ., type = "scatter") %>% 
  layout(xaxis = list(title = "Date"), 
         yaxis = list(title = "Price"))

```




























